/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:0c59efdd-15ea-4196-b8b2-3194852f1c29",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_iJwlKTjnw",
    "aws_user_pools_web_client_id": "17gmvj46km2prli3nqm0nibb4f",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "eu-north-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Doctors",
            "region": "eu-north-1"
        },
        {
            "tableName": "ChatMessages",
            "region": "eu-north-1"
        },
        {
            "tableName": "PatientCards",
            "region": "eu-north-1"
        },
        {
            "tableName": "WebSocketConnections",
            "region": "eu-north-1"
        },
        {
            "tableName": "users",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;
